# action.yml
name: 'AWS Elastic Beanstalk cli'

author: Habid Manzur

description: 'Provide eb cli commands'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  # id of input
    description: '<command>'
    required: true
    default: 'eb deploy'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
